config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  # ユーザ管理機能のパス
  resources :users, only: [:index, :edit, :update, :delete]
  resources :groups, only: [:index, :new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    # json形式
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  # グループとユーザーは多対一の関係で、中間テーブルを経由する
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.content?
        last_message.content
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
  # ユーザ名が空でないかの確認
  validates :name, presence: true
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    # ルーティングでの設定によりparamsの中にgroup_idというキーでグループのidが入るので、これを元にDBからグループを取得する
    group = Group.find(params[:group_id])
    # ajaxで送られてくる最後のメッセージのid番号を変数に代入
    last_message_id = params[:id].to_i
    # 取得したグループでのメッセージ達から、idがlast_message_idよりも新しい(大きい)メッセージ達のみを取得
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end

  def new
    @group = Group.new
    # ログインユーザを、グループに登録する（配列に要素を追加する）
    @group.users << current_user
  end

  def create
    # フォームから送信されるカラムを確認する
    # binding.pry
    # 登録は、newでもcreateでも可能
    @group = Group.new(group_params)

    # 保存が出来たかどうかの分岐
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    # 編集したグループの情報を取得
    @group = Group.find(params[:id])

    if @group.update(group_params)
      redirect_to group_messages_path(@group.id), notice: 'グループを作成しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
    @group = Group.find(params[:group_id])
  end

  def create
    @message = @group.messages.new(message_params)

    if @message.save
      respond_to do |format| # フォーマットに応じたレスポンスを作成できる
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # 何も入力されていなければ、何もしない
    return nil if params[:keyword] == ""
    # 自分の名前を除く、入力値を含むユーザ名を取得する（１０件まで）
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    # ログイン中のユーザ情報の編集が出来た時
    if current_user.update(user_params)
      # トップページに遷移する
      redirect_to root_path
    else
      # 編集出来なかった場合、もう一度戻す
      render :edit
    end
  end

  private # 他のクラスでは使えない（保守性が高まる）

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any? # エラーメッセージの有無確認
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__search.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      #chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          %p.chat-group-user__name= current_user.name

        - group.users.each do |user|
          - if current_user.name != user.name
            .chat-group-user.clearfix.js-chat-member
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}
              %p.chat-group-user__name
                = user.name 
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'messages/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 【最終課題】フリマアプリ
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %header{:class => "pcHeader"}

  %body
    = render 'layouts/notifications'
    = yield

  %footer
  フッター

app/views/messages/_main_chat.html.haml
.mainChat
  .mainChat__header
    .mainChat__header__groupname
      %p{class: 'mainChat__header__groupname__name'}
        = @group.name
      %p{class: 'mainChat__header__groupname__member'}
        = "Member:" + @group.users.pluck(:name).join(",")

    = link_to edit_group_path(@group.id) do
      Edit

  .mainChat__content
    = render @messages

  .mainChat__footer
    = form_for [@group, @message], html:{class: "mainChat__footer__inputspace"} do |f|
      = f.text_field :content, class: 'mainChat__footer__inputspace__text', placeholder: 'type a message'
      = f.label :image, class: 'mainChat__footer__inputspace__imageBtn' do
        = fa_icon "image"
        = f.file_field :image, class: 'mainChat__footer__inputspace__imageBtn__inputfile'
      = f.submit 'Send', class: 'mainChat__footer__inputspace__send'

app/views/messages/_message.html.haml
.mainChat__content__messageBox{data: {message: {id: message.id}}}
  .mainChat__content__messageBox__mAndT
    .mainChat__content__messageBox__mAndT__member
      = message.user.name
    .mainChat__content__messageBox__mAndT__time
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .mainChat__content__messageBox__message
    - if message.content.present?
      %p.mainChat__content__messageBox__message__content
        = message.content
    = image_tag message.image.url, class: 'mainChat__content__messageBox__message__image' if message.image.present?

app/views/messages/_side_bar.html.haml
.sideBar
  .sideBar__header
    .sideBar__header__accountSpace
      .sideBar__header__accountSpace__loginname
        = current_user.name
      .sideBar__header__accountSpace__iconbox
        = link_to new_group_path() do
          = fa_icon "edit"
        = link_to edit_user_path(current_user) do
          = fa_icon 'cog'

  .sideBar__content
    .sideBar__content__groupbox
      - current_user.groups.each do |group|
        = link_to group_messages_path(group), class: 'sideBar__content__groupbox__groupName' do
          .group__name
            = group.name
        %p{class: 'sideBar__content__groupbox__newMessage'}
          = group.show_last_message

app/views/messages/index.html.haml
/* 部分テンプレートの読み込み */
.wrapper
  = render "side_bar"
  = render "main_chat"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'